apiVersion: v1
kind: Pod
metadata:
  name: nginx-test1
  labels:
    app: nginx-test1
spec:
  containers:
  - name: nginx-test1
    image: nginx:1.24
    ports:
    - name: http
      containerPort: 80
